### PR TITLE
[#45] Add status and toggle status command

### PR DESCRIPTION
**Pull request by aguss787**
Implements #45 
- Add status to Task
- Add command toggle

### CODE REVIEW

**Comment by guekling** [comment]
Can you add tests for the new classes you've made, and for the new command you added in the `OrganizerParser`? Can visit [here](https://coveralls.io/builds/15943295) to see which lines you need to write tests for.

`ToggleCommand`, `ToggleCommandParser` and `OrganizerParser` can just copy from other commands and change accordingly actually. =D

Also, remember to update the UserGuide!

Thank you! (:

**Comment by aguss787** [comment]
Updated :)

**Comment by guekling** [comment]
Thank you! (:

But you forgot to update the User Guide for the `ToggleCommand`! =D

**Comment by guekling** [comment]
(:

**Review by guekling — APPROVED** [review]

**Pull request merged**
